### PR TITLE
30 create new user form user can provide personal data

### LINKED ISSUE #30: Create new User form:  user can provide personal data
New Page:
 User can provide:
- Username
- Age
- Weight
- Body type

Data saved in DB?

### PR DESCRIPTION
**Pull request by p-hannemann**
fixes #30

### CODE REVIEW

**Review by Keidaron — APPROVED** [review]
everything fine - all questions from me resolved

**Review by Tetsux3 — APPROVED** [review]

**Comment by Voltuna** [comment]
approved

**Review by Tetsux3 — APPROVED** [review]
das geht nicht besser

**Comment by p-hannemann** [comment]
@Tetsux3 please review this again, i think you might have missed something

**Review by Voltuna — APPROVED** [review]

**Pull request merged**
